# Generated by Django 4.2.3 on 2024-09-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gasoline",
            old_name="user",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="insurancepayment",
            old_name="user",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="user",
            new_name="name",
        ),
    ]
