# Generated by Django 4.2.3 on 2024-06-20 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0002_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="start_date",
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
