# Generated by Django 4.2.3 on 2024-06-20 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0003_remove_reservation_start_date_reservation_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="duration",
        ),
        migrations.AddField(
            model_name="reservation",
            name="end_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
