# Generated by Django 4.2.3 on 2024-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0003_announcement"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordIntegration",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("discord_bot_token", models.CharField(max_length=100)),
                ("discord_channel_id", models.CharField(max_length=100)),
                ("is_discord_notification_enabled", models.BooleanField(default=False)),
                ("is_status_notification_enabled", models.BooleanField(default=False)),
                (
                    "is_reservation_notification_enabled",
                    models.BooleanField(default=False),
                ),
                (
                    "is_gasoline_notification_enabled",
                    models.BooleanField(default=False),
                ),
                (
                    "is_announcement_notification_enabled",
                    models.BooleanField(default=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
