# Generated by Django 4.2.3 on 2024-06-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("status", "0004_remove_reservation_duration_reservation_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
